version: "3"

networks:
  app-tier:
    driver: bridge

services:
  postgres:
    image: postgres:alpine3.19
    networks:
      - app-tier
    env_file:
      - ./.env
    restart: always
    ports:
      - 5439:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    depends_on:
      - postgres
    build: .
    networks:
      - app-tier
    restart: always
    ports:
      - 8080:8080
    env_file:
      - ./.env

volumes:
  postgres-data:

